using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class ProjectConstantsGenerator
    {
        const string OutputPath = "Assets/Code/Generated/ProjectConstants.cs";

        [MenuItem("Tools/Regenerate Project Constants")]
        public static void GenerateFromMenu()
        {
            Generate();
            AssetDatabase.Refresh();
        }

        [InitializeOnLoadMethod]
        static void EnsureGenerated()
        {
            if (!File.Exists(OutputPath))
                Generate();
        }

        public static void Generate()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by ProjectConstantsGenerator. Do not edit manually.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Code.Generated");
            sb.AppendLine("{");
            AppendSortingLayers(sb);
            AppendLayers(sb);
            AppendTags(sb);
            sb.AppendLine("}");

            var directory = Path.GetDirectoryName(OutputPath);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            var content = sb.ToString();
            if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == content)
                return;

            File.WriteAllText(OutputPath, content);
        }

        static void AppendSortingLayers(StringBuilder sb)
        {
            sb.AppendLine("    public static class SortingLayers");
            sb.AppendLine("    {");
            foreach (var layer in SortingLayer.layers)
            {
                var id = ToIdentifier(layer.name);
                sb.AppendLine($"        public const string {id} = \"{layer.name}\";");
                sb.AppendLine($"        public const int {id}Id = {FormatSortingLayerId(layer.id)};");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        static void AppendLayers(StringBuilder sb)
        {
            sb.AppendLine("    public static class Layers");
            sb.AppendLine("    {");
            for (var i = 0; i < 32; i++)
            {
                var name = LayerMask.LayerToName(i);
                if (string.IsNullOrEmpty(name))
                    continue;

                var id = ToIdentifier(name);
                sb.AppendLine($"        public const int {id} = {i};");
                sb.AppendLine($"        public const string {id}Name = \"{name}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        static void AppendTags(StringBuilder sb)
        {
            sb.AppendLine("    public static class Tags");
            sb.AppendLine("    {");
            var tags = UnityEditorInternal.InternalEditorUtility.tags;
            if (tags.Length == 0)
                sb.AppendLine("        // No tags defined in Project Settings.");
            else
                foreach (var tag in tags)
                {
                    var id = ToIdentifier(tag);
                    sb.AppendLine($"        public const string {id} = \"{tag}\";");
                }

            sb.AppendLine("    }");
        }

        static string FormatSortingLayerId(int id) =>
            $"unchecked((int){unchecked((uint)id)}u)";

        static string ToIdentifier(string name)
        {
            var sanitized = Regex.Replace(name, @"[^\w]", "");
            if (string.IsNullOrEmpty(sanitized))
                sanitized = "_";
            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            return sanitized;
        }
    }

    sealed class ProjectConstantsAssetPostprocessor : AssetPostprocessor
    {
        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            foreach (var path in importedAssets)
            {
                if (path != "ProjectSettings/TagManager.asset")
                    continue;

                ProjectConstantsGenerator.Generate();
                return;
            }
        }
    }
}
